### PR TITLE
Upgrade to orchard core 1.3.0

### PR DESCRIPTION
**Pull request by Mehdi-Miah**

### CODE REVIEW

**Comment by Mehdi-Miah** [comment]
I checked the Robots and the redirects functionality also

**Review by peterkeating — APPROVED** [review]
Looks good, complete & tag 👍

**Comment by porgabi** [comment]
Are you certain this works the same as in previous versions? I'm trying to use the redirect feature in an OC 1.3.0/.NET 6 app to redirect users from the homepage to another URL with no success. The app previously used version `0.5.2-rc1-CI-20191115-144239` of the SEO module where the same redirect used to work, but functionality broke when I updated everything to `1.3.0`.

The redirect item is configured as follows:

image

The Home Route feature is disabled as well. Am I perhaps missing some other configuration to make this work in `1.3.0`?

**Comment by peterkeating** [comment]
@porgabi We will take a look for you :)

**Comment by peterkeating** [comment]
@porgabi Deployed a new version (1.3.1) that resolves the homepage redirect issue.

https://github.com/EtchUK/Etch.OrchardCore.SEO/pull/89

**Comment by porgabi** [comment]
Works now, thanks! 😃

**Pull request merged**
